language: minimal
os: linux
arch:
    - amd64
    - arm64
dist: bionic
sudo: enabled
script:
  - sudo apt-get update
  - sudo apt-get install --yes --no-install-recommends snapd
  - sudo snap wait system seed.loaded
  - sudo snap install --classic snapcraft
  - sudo snapcraft --destructive-mode
  - make test
