name: core18
version: 0.1
summary: Runtime environment based on Ubuntu 18.04
description: |
  The base snap based on the Ubuntu 18.04 release.
confinement: strict
type: base

parts:
  boostrap:
    plugin: make
    source: .
    build-packages:
      - shellcheck
      - wget
